project:
  type: website
  output-dir: _site
  

website:
  title: "Portfolio - Alin Sever"
  navbar:
    logo: assets/alin.png
    title: "Alin Sever"
    left:
      - text: "Home"
        href: index.qmd
  page-footer:
    center: |
      **Contact:** alinsever0@gmail.com  
      LinkedIn: https://www.linkedin.com/in/alinsever  
      GitHub: https://github.com/alinsever
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "ML Portfolio"
        href: ml-portfolio/index.qmd
        contents:

          - text: "R Labs"
            href: ml-portfolio/01_labs_R/index.qmd
            contents:
              - ml-portfolio/01_labs_R/04_svm/svm_lab_iris.qmd


          - text: "NHANES - R Project"
            href: ml-portfolio/02_nhanes_R/index.qmd
            contents:
              - ml-portfolio/02_nhanes_R/01_linear_model.qmd
              - ml-portfolio/02_nhanes_R/02_support_vector_machine.qmd


          - text: "Diabetes Readmission - Python"
            href: ml-portfolio/03_diabetes_python/index.qmd

      - text: "Standalone Projects"
        href: standalone-projects/index.qmd
        contents:
            
          - text: "Bitcoin Portfolio (R)"
            href: standalone-projects/bitcoin_portfolio_R/index.qmd

          - text: "Swiss Electricity Transition (R)"
            href: standalone-projects/swiss_electricity_transition_R/index.qmd
            contents: 
              - standalone-projects/swiss_electricity_transition_R/Swiss_Electricity_Transition_Project.qmd

      - text: "Courses & Certificates"
        href: courses/index.qmd




format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-summary: "Show code"
    freeze: auto
  pdf:
    documentclass: scrreprt
    papersize: a4
    geometry:
      - margin=2.5cm

execute:
  echo: true
  warning: false
  message: false

